version: "3"
services:
  mulearnbackend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mulearnbackend
    image: mulearnbackend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/var/log/mulearnbackend
      - /var/www/mulearnbackend/assets:/app/assets
      - /var/www/mulearnbackend/media:/app/media
      - .:/app
    env_file:
      - .env
    entrypoint: python manage.py runserver 0.0.0.0:8000
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery
    image: mulearnbackend-celery
    restart: always
    volumes:
      - /var/log/mulearnbackend:/var/log/mulearnbackend
      - /var/www/mulearnbackend/assets:/app/assets
      - /var/www/mulearnbackend/media:/app/media
    env_file:
      - .env
    command: celery -A mulearnbackend.celery worker -l info
