from django.urls import path

from . import campus_views
from . import events_views

urlpatterns = [
    path(
        "campus-details/",
        campus_views.CampusDetailsAPI.as_view(),
        name="campus-details",
    ),
    path(
        "student-level/",
        campus_views.CampusStudentInEachLevelAPI.as_view(),
        name="student-in-each-level",
    ),
    path(
        "student-level/<str:org_id>/",
        campus_views.CampusStudentInEachLevelAPI.as_view(),
        name="student-in-each-level-individual",
    ),
    path(
        "student-details/",
        campus_views.CampusStudentDetailsAPI.as_view(),
        name="student-details",
    ),
    path(
        "student-details/csv/",
        campus_views.CampusStudentDetailsCSVAPI.as_view(),
        name="student-details-csv",
    ),
    path(
        "weekly-karma/",
        campus_views.WeeklyKarmaAPI.as_view(),
        name="weekly-karma-insights",
    ),
    path(
        "weekly-karma/<str:org_id>/",
        campus_views.WeeklyKarmaAPI.as_view(),
        name="weekly-karma-insights-individual",
    ),
    path(
        "change-student-type/<str:member_id>/",
        campus_views.ChangeStudentTypeAPI.as_view(),
        name="change-student-type",
    ),
    path(
        "transfer-lead-role/",
        campus_views.TransferLeadRoleAPI.as_view(),
        name="transfer-lead-role",
    ),
    path(
        "transfer-enabler-role/",
        campus_views.TransferEnablerRoleAPI.as_view(),
        name="transfer-enabler-role",
    ),
    path(
        "transfer-ig-role/",
        campus_views.TransferIGRoleAPI.as_view(),
        name="transfer-ig-role",
    ),
    path(
        "events/",
        events_views.CampusEventsAPI.as_view(),
        name="campus-events",
    ),
    path(
        "events/distribution/",
        events_views.CampusEventDistributionAPI.as_view(),
        name="campus-event-distribution",
    ),
    path(
        "execom/",
        events_views.CampusExecomAPI.as_view(),
        name="campus-execom",
    ),
    path(
        "execom/<str:member_id>/",
        events_views.CampusExecomAPI.as_view(),
        name="campus-execom-delete",
    ),
    path(
        "<str:org_id>/",
        campus_views.CampusDetailsPublicAPI.as_view(),
        name="campus-details-individual",
    ),
    
    path(
        "<str:org_id>/campus-details/",
        campus_views.CampusDetailsAPI.as_view(),
        name="campus-details",
    ),
    path(
        "<str:org_id>/leaderboard/",
        campus_views.CampusStudentLeaderboardAPI.as_view(),
        name="campus-student-leaderboard",
    ),
    path(
        "<str:org_id>/karma-by-cluster/",
        campus_views.CampusKarmaByClusterAPI.as_view(),
        name="campus-karma-by-cluster",
),

]
