from django.urls import path, include
from api.calendar.dashboard_calendar_view import DashboardCalendarAPI

# app_name will help us do a reverse look-up latter.
urlpatterns = [
    path("calendar/events/", DashboardCalendarAPI.as_view()),
    path("home/", include("api.dashboard.home.urls")),
    path("user/", include("api.dashboard.user.urls")),
    path("zonal/", include("api.dashboard.zonal.urls")),
    path("district/", include("api.dashboard.district.urls")),
    path("campus/", include("api.dashboard.campus.urls")),
    path("enabler/", include("api.dashboard.enabler.urls")),
    path("roles/", include("api.dashboard.roles.urls")),
    path("ig/", include("api.dashboard.ig.urls")),
    path("task/", include("api.dashboard.task.urls")),
    path("profile/", include("api.dashboard.profile.urls")),
    # path("lc/", include("api.dashboard.lc.urls")),
    path("learningcircle/", include("api.dashboard.learningcircle.urls")),
    path("referral/", include("api.dashboard.referral.urls")),
    path("college/", include("api.dashboard.college.urls")),
    path("karma-voucher/", include("api.dashboard.karma_voucher.urls")),
    path("location/", include("api.dashboard.location.urls")),
    path("organisation/", include("api.dashboard.organisation.urls")),
    path("dynamic-management/", include("api.dashboard.dynamic_management.urls")),
    path("error-log/", include("api.dashboard.error_log.urls")),
    path("affiliation/", include("api.dashboard.affiliation.urls")),
    path("channels/", include("api.dashboard.channels.urls")),
    path("discord-moderator/", include("api.dashboard.discord_moderator.urls")),
    path("events/", include("api.dashboard.events.urls")),
    path("coupon/", include("api.dashboard.coupon.urls")),
    path("projects/", include("api.dashboard.projects.urls")),
    path("achievement/", include("api.dashboard.achievement.urls")),
    path("skill/", include("api.dashboard.skill.urls")),
    path("task-report/", include("api.dashboard.task_report.urls")),
    path("media-content/", include("api.dashboard.media_content.urls")),

    path("category/", include("api.dashboard.category.urls")),
    path("mentor/", include("api.dashboard.mentor.urls")),
    path("intern/", include("api.dashboard.intern.urls")),
    path("manage-interns/", include("api.dashboard.manage_interns.urls")),
    path("company/", include("api.dashboard.company.urls")),
    path("feature/", include("api.dashboard.feature.urls")),
    path("career-lab/", include("api.dashboard.career_lab.urls")),
    # mentorship/ has been consolidated into mentor/ — do not re-add
]
