from rest_framework import serializers
from db.intern import InternTask
from db.user import User

COMPLEXITY_WEIGHT_MAP = {'LOW': 1, 'MEDIUM': 2, 'HIGH': 3, 'CRITICAL': 5}

class UserPrimaryKeyRelatedField(serializers.PrimaryKeyRelatedField):
    def to_internal_value(self, data):
        # Try to retrieve user by muid first, then fallback to uuid (pk)
        user = User.objects.filter(muid=data).first()
        if user:
            return user
        try:
            return super().to_internal_value(data)
        except serializers.ValidationError:
            raise serializers.ValidationError(
                f"User with muid or user_id '{data}' does not exist."
            )

class ManageInternTaskSerializer(serializers.ModelSerializer):
    guild = serializers.CharField(source='team', write_only=True, required=False)
    assigned_to = UserPrimaryKeyRelatedField(queryset=User.objects.all())
    iso_week = serializers.IntegerField(required=False)
    complexity_score = serializers.SerializerMethodField()
    
    class Meta:
        model = InternTask
        fields = [
            'id', 'title', 'description', 'category', 'complexity',
            'complexity_score', 'assigned_to', 'status', 'team', 'guild',
            'deadline', 'iso_week', 'output_link', 'karma_awarded',
            'is_verified', 'verified_by_id', 'created_at'
        ]
        read_only_fields = ['created_at', 'is_verified', 'verified_by_id']

    def get_complexity_score(self, obj):
        return COMPLEXITY_WEIGHT_MAP.get(obj.complexity, 1)

    def validate(self, attrs):
        # Auto-calculate iso_week from deadline if not provided
        if 'deadline' in attrs and 'iso_week' not in attrs:
            attrs['iso_week'] = attrs['deadline'].isocalendar()[1]
        
        return attrs

    def create(self, validated_data):
        user_id = self.context.get('user_id')
        validated_data['created_by_id'] = user_id
        validated_data['updated_by_id'] = user_id
        
        # In case iso_week wasn't passed and wasn't generated by deadline
        if 'iso_week' not in validated_data and 'deadline' in validated_data:
            validated_data['iso_week'] = validated_data['deadline'].isocalendar()[1]
            
        return super().create(validated_data)

    def update(self, instance, validated_data):
        user_id = self.context.get('user_id')
        validated_data['updated_by_id'] = user_id
        return super().update(instance, validated_data)
