"""
Django settings for mulearnbackend project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

from decouple import config as decouple_config

import logging

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = decouple_config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = decouple_config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = decouple_config(
    "ALLOWED_HOSTS", cast=lambda v: [s.strip() for s in v.split(",")]
)

# System admin applied to rows when their parent user instance is deleted
SYSTEM_ADMIN_ID = decouple_config("SYSTEM_ADMIN_ID")

# Application definition

INSTALLED_APPS = [
    "daphne",
    # 'django.contrib.admin',
    "django.contrib.auth",
    "django.contrib.contenttypes",
    # 'django.contrib.sessions',
    # 'django.contrib.messages',
    "django.contrib.staticfiles",
    "rest_framework",
    # custom apps
    "debug_toolbar",
    "utils.apps.UtilsConfig",
    "api.apps.ApiConfig",
    "corsheaders",
    "db",
    "drf_spectacular",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.common.CommonMiddleware",
    "mulearnbackend.middlewares.UniversalErrorHandlerMiddleware",
]

ROOT_URLCONF = "mulearnbackend.urls"
CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "muLearn API",
    "DESCRIPTION": "API documentation for the muLearn Platform backend.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_PATCH": True,
    "COMPONENT_SPLIT_COMMAND": True,
    "ENUM_NAME_POSTFIX": "_Enum",
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": True,
    },
    "SERVE_PERMISSIONS": ["rest_framework.permissions.IsAdminUser"] if not decouple_config("ENABLE_SWAGGER", default=False, cast=bool) else ["rest_framework.permissions.AllowAny"],
    "SECURITY": [
        {
            "jwtAuth": [],
        }
    ],
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "jwtAuth": {
                "type": "apiKey",
                "in": "header",
                "name": "Authorization",
                "description": 'JWT Token Authentication. Enter **"Bearer \u003ctoken\u003e"**',
            }
        }
    },
    "SCHEMA_PATH_PREFIX": r"/api/v1/",
    "POSTPROCESSING_HOOKS": ["utils.spectacular.custom_postprocessing_hook"],
    "DEFAULT_FORMAT": "json",
}


# paginator settings
PAGE_SIZE = 10
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ASGI_APPLICATION = "mulearnbackend.asgi.application"

WSGI_APPLICATION = "mulearnbackend.wsgi.application"

REDIS_HOST = decouple_config("REDIS_HOST")
REDIS_PORT = decouple_config("REDIS_PORT")

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, REDIS_PORT)],
        },
    },
}

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": decouple_config("DATABASE_ENGINE"),
        "NAME": decouple_config("DATABASE_NAME"),
        "USER": decouple_config("DATABASE_USER"),
        "PASSWORD": decouple_config("DATABASE_PASSWORD"),
        "HOST": decouple_config("DATABASE_HOST"),
        "PORT": decouple_config("DATABASE_PORT"),
        # Must stay 0 under ASGI. Django's ASGIHandler wraps every request in a
        # ThreadSensitiveContext, so asgiref gives each request its own thread,
        # and DB connections are thread-local. A non-zero CONN_MAX_AGE tells
        # close_old_connections() to keep the connection "for reuse" by a thread
        # that is about to be destroyed, so it leaks until GC finalises it.
        # With unbounded request concurrency that exhausts max_connections.
        "CONN_MAX_AGE": 0,
    }
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "my_cache_table",
    },
    "redis": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    },
}

CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/2"
CELERY_RESULT_BACKEND = f"redis://{REDIS_HOST}:{REDIS_PORT}/2"

# Use the Redis cache as the default cache
CACHES["default"] = CACHES["redis"]

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LOG_PATH = decouple_config("LOGGER_DIR_PATH")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "request_log": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": f"{LOG_PATH}/request.log",
            "formatter": "verbose",
        },
        "error_log": {
            "level": "ERROR",
            "class": "logging.FileHandler",
            "filename": f"{LOG_PATH}/error.log",
            "formatter": "verbose",
        },
        "sql_log": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": f"{LOG_PATH}/sql.log",
            "formatter": "verbose",
        },
        "root_log": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": f"{LOG_PATH}/root.log",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django.request": {
            "handlers": ["request_log"],
            "level": "INFO",
            "propagate": True,
        },
        "django": {
            "handlers": ["error_log"],
            "level": "ERROR",
            "propagate": True,
        },
        "django.db.backends": {
            "handlers": ["sql_log"],
            "level": "DEBUG",
            "propagate": True,
        },
        "": {
            "handlers": ["root_log"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {message}",
            "style": "{",
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "assets")
STATIC_URL = "/muback-static/"

MEDIA_URL = "/muback-media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Email Sending
EMAIL_BACKEND = decouple_config("EMAIL_BACKEND")
EMAIL_HOST = decouple_config("EMAIL_HOST")
EMAIL_HOST_USER = decouple_config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = decouple_config("EMAIL_HOST_PASSWORD")
EMAIL_PORT = decouple_config("EMAIL_PORT")
EMAIL_USE_TLS = decouple_config("EMAIL_USE_TLS")
FROM_MAIL = decouple_config("FROM_MAIL")
FR_DOMAIN_NAME = decouple_config("FR_DOMAIN_NAME")

WADHWANI_CLIENT_AUTH_URL = decouple_config("WADHWANI_CLIENT_AUTH_URL")
WADHWANI_CLIENT_SECRET = decouple_config("WADHWANI_CLIENT_SECRET")
WADHWANI_BASE_URL = decouple_config("WADHWANI_BASE_URL")

RAZORPAY_ID = decouple_config("RAZORPAY_ID")
RAZORPAY_SECRET = decouple_config("RAZORPAY_SECRET")

QSEVERSE_BASE_URL = decouple_config("QSEVERSE_BASE_URL")
QSEVERSE_API_KEY = decouple_config("QSEVERSE_API_KEY")

BACKEND_API_KEY = decouple_config("BACKEND_API_KEY")

DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"

import socket

hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
INTERNAL_IPS = [f"{ip[:-1]}1" for ip in ips] + ["127.0.0.1", "10.0.2.2"]
DEFAULT_CHARSET = "utf-8"
from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'intern-daily-status-cron': {
        'task': 'mu_celery.intern_cron.intern_daily_status_cron',
        'schedule': crontab(hour=0, minute=5),
    },
    'intern-task-deadline-cron': {
        'task': 'mu_celery.intern_cron.intern_task_deadline_cron',
        'schedule': crontab(hour=0, minute=10),
    },
    'update-alumni-status-cron': {
        'task': 'mu_celery.alumni_cron.update_alumni_status_cron',
        'schedule': crontab(hour=0, minute=15),
    },
    'transition-mentorship-session-statuses': {
        'task': 'mu_celery.mentor_tasks.transition_mentorship_session_statuses',
        'schedule': crontab(minute='*/15'),
    },
    'expire-stale-mentor-applications': {
        'task': 'mu_celery.mentor_tasks.expire_stale_applications',
        'schedule': crontab(hour=0, minute=20),
    },
    'expire-stale-mentor-grants': {
        'task': 'mu_celery.mentor_tasks.expire_stale_grants',
        'schedule': crontab(hour=0, minute=25),
    },
    'expire-stale-company-jobs': {
        'task': 'mu_celery.company_tasks.expire_stale_jobs',
        'schedule': crontab(hour=0, minute=30),
    },
    'transition-event-statuses': {
        'task': 'mu_celery.event_cron.transition_event_statuses_task',
        'schedule': crontab(hour=0, minute=35),
    },
    # Keeps organization.cached_total_karma / .cached_member_count fresh for the
    # campus search sort. Every 15 minutes: these drive ranking, not correctness,
    # so some lag is acceptable, but a daily refresh would visibly stale the
    # leaderboard.
    'refresh-org-aggregates-cron': {
        'task': 'mu_celery.org_aggregates_cron.refresh_org_aggregates',
        'schedule': crontab(minute='*/15'),
    },
    # Keeps learning_circle.cached_total_karma / .cached_rank fresh for the
    # circle detail view's ranking display. Same 15-minute cadence and lag
    # rationale as refresh-org-aggregates-cron above.
    'refresh-learning-circle-aggregates-cron': {
        'task': 'mu_celery.learning_circle_aggregates_cron.refresh_learning_circle_aggregates',
        'schedule': crontab(minute='*/15'),
    },
}
